### ISSUE TITLE
Does this upgrade directly from dolphiq site map plugin?

### ISSUE THREAD

**Issue by CreateSean** [HOMMinteractive/hommxmlsitemap#8]
There's a [comment on a github](https://github.com/Dolphiq/craft3-plugin-sitemap/issues/62#issuecomment-1252471330) issue suggesting that this plugin is a direct upgrade from the dolphiq xml sitemap plugin.

I didn't see anything in your readme to confirm this. Please advise.

**Comment by ammannbe** [comment]
This plugin is not a direct replacement/upgrade of Dolphiq/craft3-plugin-sitemap.
You can use this plugin as an alternative as it has some similarities, but there's not a direct upgrade provided. You need to manually set the necessary settings.

But it shouldn't take a lot of time as the settings page is very simple and also similar to the dolphiq plugin.
