### ISSUE TITLE
No XML Generated

### ISSUE THREAD

**Issue by beckbailey** [HOMMinteractive/hommxmlsitemap#9]
I'm using:

- CraftCMS 4.4.6.1
- HOMM XML Sitemap 1.0.3

I have 2 structures and 1 single checked to be included in the sitemap and the file at mydomain/sitemap.xml is empty.

**Comment by Jolins123** [comment]
I'm having the same issue with craft 4.4.7.1

**Comment by ammannbe** [comment]
Unfortunately I can't reproduce this behavior.
I'll do some tests if I have time.

Have you made sure that you can access the sites by URL?

Maybe you can also do some debuggin on your environment. This is the part where the sitemap gets generated: https://github.com/HOMMinteractive/hommxmlsitemap/blob/42b122d9a81a9520fcd4feb3fc879186aeed391e/src/controllers/SitemapController.php#L58-L174

**Comment by beckbailey** [comment]
I was able to verify this is working in my production environment. Locally, I still have the issue where the XML sitemap loads but contains no data. I can access the site by URL. As long as it works in the production environment, it isn't an issue for me.

**Comment by beckbailey** [comment]
I was able to verify this is working in my production environment. Locally, I still have the issue where the XML sitemap loads but contains no data. I can access the site by URL. As long as it works in the production environment, it isn't an issue for me.

**Comment by raitisg** [comment]
I have the same issue:

- Craft Pro 4.5.13
- HOMM XML Sitemap 1.0.3

It works locally, but not in production.

**Comment by ammannbe** [comment]
@raitisg if it works locally, but not in production, this is probably **not** the same problem. It's the opposite case.
Please open a separate issue with more details provided. Thanks
